ARG NODE_VERSION=24.16.0
ARG ALPINE_VERSION=3.24

FROM node:${NODE_VERSION}-alpine${ALPINE_VERSION} AS builder

RUN apk update && apk upgrade
RUN apk add --no-cache jq python3 make g++ linux-headers

ENV WORKDIR="/contract"
ENV NODE_ENV="development"

WORKDIR $WORKDIR

COPY ./.npmrc ./
COPY ./package*.json ./
COPY ./tsconfig.json ./
COPY ./src/ ./src/

RUN --mount=type=secret,id=TOKEN NPM_TOKEN=$(cat /run/secrets/TOKEN) npm ci --include=optional && npm cache clean --force && chown -R node:node .
RUN npm run build && npm run build:contract:docker

ARG NODE_VERSION=24.16.0
ARG ALPINE_VERSION=3.24

FROM node:${NODE_VERSION}-alpine${ALPINE_VERSION} AS production

RUN apk update && apk upgrade
RUN apk add --no-cache jq

# --------------------
# BASE IMAGE OVERRIDES
# --------------------
RUN mkdir -p /tmp/npm-patches && \
  cd /tmp/npm-patches && \
  npm pack brace-expansion@5.0.9 ip-address@10.3.1 sigstore@4.1.1 tar@7.5.21 undici@6.27.0 pacote@21.5.1 && \
    for pkg in brace-expansion ip-address sigstore tar undici pacote; do \
      rm -rf "/usr/local/lib/node_modules/npm/node_modules/$pkg"; \
    done && \
    mkdir -p /usr/local/lib/node_modules/npm/node_modules/brace-expansion && \
    tar -xzf brace-expansion-5.0.9.tgz -C /usr/local/lib/node_modules/npm/node_modules/brace-expansion --strip-components=1 && \
    mkdir -p /usr/local/lib/node_modules/npm/node_modules/ip-address && \
    tar -xzf ip-address-10.3.1.tgz -C /usr/local/lib/node_modules/npm/node_modules/ip-address --strip-components=1 && \
    mkdir -p /usr/local/lib/node_modules/npm/node_modules/sigstore && \
    tar -xzf sigstore-4.1.1.tgz -C /usr/local/lib/node_modules/npm/node_modules/sigstore --strip-components=1 && \
    mkdir -p /usr/local/lib/node_modules/npm/node_modules/tar && \
    tar -xzf tar-7.5.21.tgz -C /usr/local/lib/node_modules/npm/node_modules/tar --strip-components=1 && \
    mkdir -p /usr/local/lib/node_modules/npm/node_modules/undici && \
    tar -xzf undici-6.27.0.tgz -C /usr/local/lib/node_modules/npm/node_modules/undici --strip-components=1 && \
    mkdir -p /usr/local/lib/node_modules/npm/node_modules/pacote && \
    tar -xzf pacote-21.5.1.tgz -C /usr/local/lib/node_modules/npm/node_modules/pacote --strip-components=1 && \
    rm -rf /tmp/npm-patches

ENV WORKDIR="/contract"
ENV NODE_ENV="production"

WORKDIR $WORKDIR

COPY --from=builder --chown=node:node ${WORKDIR}/contracts ./
COPY --from=builder --chown=node:node ${WORKDIR}/.npmrc ./
COPY --from=builder --chown=node:node ${WORKDIR}/package-lock.json ./npm-shrinkwrap.json

RUN --mount=type=secret,id=TOKEN NPM_TOKEN=$(cat /run/secrets/TOKEN) npm ci --include=optional && npm cache clean --force && chown -R node:node .
