ARG NODE_VERSION=24
FROM node:${NODE_VERSION}-alpine AS builder

RUN apk update && apk upgrade
RUN apk add jq

ENV WORKDIR="/contract"
ENV NODE_ENV="development"

WORKDIR $WORKDIR

COPY ./.npmrc ./
COPY ./package*.json ./
COPY ./tsconfig.json ./
COPY ./src/ ./src/

RUN --mount=type=secret,id=TOKEN NPM_TOKEN=$(cat /run/secrets/TOKEN) npm ci && npm cache clean --force && chown -R node:node .
RUN
RUN npm run build && npm run build:contract:docker

ARG NODE_VERSION=24
FROM node:${NODE_VERSION}-alpine AS production

RUN apk update && apk upgrade
RUN apk add jq

ENV WORKDIR="/contract"
ENV NODE_ENV="production"

WORKDIR $WORKDIR

COPY --from=builder --chown=node:node ${WORKDIR}/contracts ./
RUN npm uninstall @decaf-ts/for-http @decaf-ts/for-nano @decaf-ts/for-typeorm
COPY --from=builder --chown=node:node ${WORKDIR}/.npmrc ./

RUN --mount=type=secret,id=TOKEN NPM_TOKEN=$(cat /run/secrets/TOKEN) npm ci && npm cache clean --force && chown -R node:node .
