import { InfrastructureConfig, OnboardConfig } from "./types";

export const DefaultInfrastructureConfig: InfrastructureConfig = {
  dockerSocketPath: "/var/run/docker.sock",
  participatingOrgs: "orgc",
  onPrem: false,
  enableCollections: false,
  deploymentPlatform: "docker",
  orgName: "orga",
  orgDomain: "simple.internal",
  dockerComposePath: "../../docker/pla-docker-compose.yaml",
  logLevel: "debug",
  tools: {
    image: "dregistry.pdmfc.com/decaf-ts/fabric-weaver:weaver-2.5.12-latest",
  },
  tls: {
    image: "ghcr.io/pharmaledgerassoc/ptp-infrastructure:fabric-ca-latest",
    port: 7000,
    operationsAddress: "127.0.0.1:8010",
    csrHosts:
      "0.0.0.0,localhost,127.0.0.1,orga-tls,*.orga.org",
    user: "orga.tls",
    secret: "SomeRandomPassword",
  },
  ca: {
    image: "ghcr.io/pharmaledgerassoc/ptp-infrastructure:fabric-ca-latest",
    port: 7010,
    operationsAddress: "127.0.0.1:8010",
    csrHosts:
      "0.0.0.0,localhost,127.0.0.1,orga-ca,*.orga.org",
    user: "orga.ca",
    secret: "SomeRandomPassword",
    admin: "orga.admin",
    adminSecret: "SomeRandomPassword",
    adminCsrHosts:
      "0.0.0.0,localhost,127.0.0.1,orga-ca,*.orga.org",
  },
  org: {
    country: "GB",
    state: "Greater London",
    locality: "London",
    organization: "OrgA Organization",
    organizationUnit: "Fabric for Pharmaledger",
  },
  hsm: {
    enabled: false,
    lib: "/usr/lib/softhsm/libsofthsm2.so",
    label: "orgahsm",
    pin: 98765434,
    altId: "",
    soPin: 1235,
  },
  orderer0: {
    port: 7020,
    osnPort: 7030,
    image: "ghcr.io/pharmaledgerassoc/ptp-infrastructure:fabric-orderer-latest",
    operationsAddress: "127.0.0.1:8010",
    csrHosts:
      "0.0.0.0,localhost,127.0.0.1,orga-orderer-0,*.orga.org",
    user: "orga.orderer0",
    secret: "SomeRandomPassword",
  },
  orderer1: {
    port: 7021,
    osnPort: 7031,
    image: "ghcr.io/pharmaledgerassoc/ptp-infrastructure:fabric-orderer-latest",
    operationsAddress: "127.0.0.1:8010",
    csrHosts:
      "0.0.0.0,localhost,127.0.0.1,orga-orderer-1,*.orga.org",
    user: "orga.orderer1",
    secret: "SomeRandomPassword",
  },
  orderer2: {
    port: 7022,
    osnPort: 7032,
    image: "ghcr.io/pharmaledgerassoc/ptp-infrastructure:fabric-orderer-latest",
    operationsAddress: "127.0.0.1:8010",
    csrHosts:
      "0.0.0.0,localhost,127.0.0.1,orga-orderer-2,*.orga.org",
    user: "orga.orderer2",
    secret: "SomeRandomPassword",
  },
  peer0: {
    image: "ghcr.io/pharmaledgerassoc/ptp-infrastructure:fabric-peer-latest",
    port: 7050,
    user: "orga.peer0",
    secret: "SomeRandomPassword",
    chaincodePort: 7060,
    couchdbPort: 7040,
    couchdbUser: "admin",
    couchdbSecret: "adminpw",
    couchdbImage: "couchdb:latest",
    operationsAddress: "127.0.0.1:8010",
    csrHosts:
      "0.0.0.0,localhost,127.0.0.1,orga-peer-0,*.orga.org",
  },
  peer1: {
    image: "ghcr.io/pharmaledgerassoc/ptp-infrastructure:fabric-peer-latest",
    port: 7051,
    user: "orga.peer1",
    secret: "SomeRandomPassword",
    chaincodePort: 7061,
    couchdbPort: 7041,
    couchdbUser: "admin",
    couchdbSecret: "adminpw",
    couchdbImage: "couchdb:latest",
    operationsAddress: "127.0.0.1:8010",
    csrHosts:
      "0.0.0.0,localhost,127.0.0.1,orga-peer-1,*.orga.org",
  },
  peer2: {
    image: "ghcr.io/pharmaledgerassoc/ptp-infrastructure:fabric-peer-latest",
    port: 7052,
    user: "orga.peer2",
    secret: "SomeRandomPassword",
    chaincodePort: 7062,
    couchdbPort: 7042,
    couchdbUser: "admin",
    couchdbSecret: "adminpw",
    couchdbImage: "couchdb:latest",
    operationsAddress: "127.0.0.1:8010",
    csrHosts:
      "0.0.0.0,localhost,127.0.0.1,orga-peer-2,*.orga.org",
  },
  channel: {
    profile: "OrgAChannel",
    name: "simple-channel",
  },
  onPremChannel: {
    profile: "OrgAOnPremChannel",
    name: "simple-on-prem-channel",
  },
  contract: {
    name: "simple-chaincode",
    user: "orga.ccaas",
    secret: "SomeRandomPassword",
    image: "ghcr.io/pharmaledgerassoc/ptp-toolkit:contract-latest",
    port: 7070,
    csrHosts:
      "0.0.0.0,localhost,127.0.0.1,orga-ccaas-simple-chaincode,orga-ccaas-simple-on-prem-chaincode,*.orga.org",
    tag: "latest",
    update: false,
    version: "1.0",
    maxRecvMsgSize: 15728640,
    maxSendMsgSize: 15728640,
  },
  onPremContract: {
    name: "simple-on-prem-chaincode",
    user: "orga.ccaas",
    secret: "SomeRandomPassword",
    image: "ghcr.io/pharmaledgerassoc/ptp-toolkit:contract-latest",
    port: 7080,
    csrHosts:
      "0.0.0.0,localhost,127.0.0.1,orga-ccaas-simple-chaincode,*.orga.org",
    tag: "latest",
    update: false,
    version: "1.0",
    maxRecvMsgSize: 15728640,
    maxSendMsgSize: 15728640,
  },
};

export const DefaultOnboardPartnerConfig: OnboardConfig = {
  dockerSocketPath: "/var/run/docker.sock",
  deploymentPlatform: "docker",
  enableCollections: false,
  orgName: "orgc",
  logLevel: "debug",
  onPrem: false,
  dockerComposePath: "../../docker/org-docker-compose.yaml",
  tools: {
    image: "dregistry.pdmfc.com/decaf-ts/fabric-weaver:weaver-2.5.12-latest",
  },
  tls: {
    image: "ghcr.io/pharmaledgerassoc/ptp-infrastructure:fabric-ca-latest",
    port: 7100,
    operationsAddress: "127.0.0.1:8010",
    csrHosts: "0.0.0.0,localhost,127.0.0.1,orgc-tls,*.orgc.org",
    user: "orgc.tls",
    secret: "SomeRandomPassword",
  },
  ca: {
    image: "ghcr.io/pharmaledgerassoc/ptp-infrastructure:fabric-ca-latest",
    port: 7110,
    operationsAddress: "127.0.0.1:8010",
    csrHosts: "0.0.0.0,localhost,127.0.0.1,orgc-ca,*.orgc.org",
    user: "orgc.ca",
    secret: "SomeRandomPassword",
    admin: "orgc.admin",
    adminSecret: "SomeRandomPassword",
    adminCsrHosts: "0.0.0.0,localhost,127.0.0.1,orgc-ca,*.orgc.org",
  },
  org: {
    country: "GB",
    state: "Greater London",
    locality: "London",
    organization: "OrgC Organization",
    organizationUnit: "Fabric for Pharmaledger",
  },
  hsm: {
    enabled: false,
    lib: "/usr/lib/softhsm/libsofthsm2.so",
    label: "orgchsm",
    pin: 98765434,
    altId: "",
    soPin: 1235,
  },
  peer0: {
    image: "ghcr.io/pharmaledgerassoc/ptp-infrastructure:fabric-peer-latest",
    port: 7150,
    user: "orgc.peer0",
    secret: "SomeRandomPassword",
    chaincodePort: 7160,
    couchdbPort: 7140,
    couchdbUser: "admin",
    couchdbSecret: "adminpw",
    couchdbImage: "couchdb:latest",
    operationsAddress: "127.0.0.1:8010",
    host: "",
    csrHosts: "0.0.0.0,localhost,127.0.0.1,orgc-peer-0,*.orgc.org",
  },
  channel: {
    profile: "OrgAChannel",
    name: "simple-channel",
  },
  onPremChannel: {
    profile: "OrgAOnPremChannel",
    name: "simple-on-prem-channel",
  },
  contract: {
    name: "simple-chaincode",
    user: "orgc.ccaas",
    secret: "SomeRandomPassword",
    image: "ghcr.io/pharmaledgerassoc/ptp-toolkit:contract-latest",
    port: 7170,
    csrHosts: "0.0.0.0,localhost,127.0.0.1,orgc-ccaas-simple-chaincode,*.orgc.org",
    tag: "latest",
    update: true,
    version: "1.0",
    maxRecvMsgSize: 15728640,
    maxSendMsgSize: 15728640,
  },
  onPremContract: {
    name: "simple-on-prem-chaincode",
    user: "orgc.ccaas",
    secret: "SomeRandomPassword",
    image: "ghcr.io/pharmaledgerassoc/ptp-toolkit:contract-latest",
    port: 7180,
    csrHosts:
      "0.0.0.0,localhost,127.0.0.1,orgc-ccaas-simple-on-prem-chaincode,*.orgc.org",
    tag: "latest",
    update: true,
    version: "1.0",
    maxRecvMsgSize: 15728640,
    maxSendMsgSize: 15728640,
  },
  pla: {
    orgName: "orga",
    peerAddress: "orga-peer-0",
    ordererAddress: "orga-orderer-0",
    toolsAddress: "orga-tools",
    tlsPort: 7000,
    ordererPort: 7020,
  },
};
