import { execFileSync } from "child_process";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";

const ROOT = path.join(__dirname, "..", "..");

const CONTRACT_DIR = path.join(
  ROOT,
  "docker",
  "infrastructure",
  "chaincode",
  "global"
);
const CONTRACT_PACKAGE_JSON = path.join(CONTRACT_DIR, "package.json");
const CONTRACT_ENTRY = path.join(CONTRACT_DIR, "contract", "index.cjs");
const CONTRACT_COLLECTIONS_CONFIG = path.join(
  CONTRACT_DIR,
  "META-INF",
  "collections_config.json"
);

const TRACKED_MODELS_FOLDER = path.join(
  ROOT,
  "lib",
  "cjs",
  "contract",
  "trackedModels"
);

const DECAF_CLI = path.join(
  ROOT,
  "node_modules",
  "@decaf-ts",
  "cli",
  "lib",
  "cjs",
  "bin",
  "cli.cjs"
);

// snapshot of the collections generated by
// `npm run extract:collections` (with --mspIds '["orgb","orgc"]' --mainMspId orga)
// against the current contract models. update whenever the contract changes.
const EXPECTED_COLLECTIONS = [
  {
    name: "ptp-history-mirror",
    policy: "OR('orga.member')",
    requiredPeerCount: 0,
    maxPeerCount: 0,
    blockToLive: 0,
    memberOnlyRead: true,
    memberOnlyWrite: false,
    endorsementPolicy: {
      signaturePolicy: "OR('orga.peer')",
    },
  },
  {
    name: "mirror-collection",
    policy: "OR('orga.peer.member')",
    requiredPeerCount: 0,
    maxPeerCount: 0,
    blockToLive: 0,
    memberOnlyRead: true,
    memberOnlyWrite: false,
    endorsementPolicy: {
      signaturePolicy: "OR('orga.peer.peer')",
    },
  },
  {
    name: "ptp-historyOrgb",
    policy: "OR('orgb.member','orga.member')",
    requiredPeerCount: 1,
    maxPeerCount: 2,
    blockToLive: 0,
    memberOnlyRead: true,
    memberOnlyWrite: true,
    endorsementPolicy: {
      signaturePolicy: "AND('orgb.peer','orga.peer')",
    },
  },
  {
    name: "ptp-historyOrgc",
    policy: "OR('orgc.member','orga.member')",
    requiredPeerCount: 1,
    maxPeerCount: 2,
    blockToLive: 0,
    memberOnlyRead: true,
    memberOnlyWrite: true,
    endorsementPolicy: {
      signaturePolicy: "AND('orgc.peer','orga.peer')",
    },
  },
  {
    name: "decaf-namespaceOrgb",
    policy: "OR('orgb.member','orga.member')",
    requiredPeerCount: 1,
    maxPeerCount: 2,
    blockToLive: 0,
    memberOnlyRead: true,
    memberOnlyWrite: true,
    endorsementPolicy: {
      signaturePolicy: "AND('orgb.peer','orga.peer')",
    },
  },
  {
    name: "decaf-namespaceOrgc",
    policy: "OR('orgc.member','orga.member')",
    requiredPeerCount: 1,
    maxPeerCount: 2,
    blockToLive: 0,
    memberOnlyRead: true,
    memberOnlyWrite: true,
    endorsementPolicy: {
      signaturePolicy: "AND('orgc.peer','orga.peer')",
    },
  },
];

function sortByNames(
  collections: Array<Record<string, unknown>>
): Array<Record<string, unknown>> {
  return [...collections].sort((a, b) =>
    String(a["name"]).localeCompare(String(b["name"]))
  );
}

describe("contract collections config", () => {});
